spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security1
    username: root
    password: 2705
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
